services:
  blogging-api:
    image: brisabrasadora/blogging-api:latest
    container_name: api
    restart: always
    environment:
      PORT: 3000
      NODE_ENV: production
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: vivianna12
      DB_LOGGING: all
      DB_NAME: postgres
    ports:
      - 3000:3000
    depends_on:
      - "postgres-db"
      
  postgres-db:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: vivianna12 #Credenciales para el super usuario de la BBDD
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blogging-api.com
      PGADMIN_DEFAULT_PASSWORD: brisabrasadora11 #Credenciales para acceder la GUI
      PGADMIN_LISTEN_PORT: 80 #Puerto por el que escucha internamente
    ports:
      - 8080:80 #Se accede a este contenedor externamente por el 8080
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - "postgres-db"