name: Publush image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build -t brisabrasadora/blogging-api:latest .
      - name: Publish image
        run: |
          docker login -u brisabrasadora -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push brisabrasadora/blogging-api:latest